# Generated by Django 5.1.7 on 2025-03-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superb_ock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='golf_round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=20)),
            ],
        ),
    ]
