# Generated by Django 5.1.7 on 2025-03-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superb_ock', '0002_golf_round'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='golf_round',
            new_name='GolfRound',
        ),
    ]
