# Generated by Django 5.1.7 on 2025-03-12 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superb_ock', '0003_rename_golf_round_golfround'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolfCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('ocks', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='golfround',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='golfround',
            name='holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shots_taken', models.IntegerField(blank=True, null=True)),
                ('stableford', models.IntegerField(blank=True, null=True)),
                ('handicap_index', models.FloatField()),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superb_ock.hole')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superb_ock.player')),
            ],
        ),
    ]
