# Generated by Django 5.1.7 on 2025-03-16 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superb_ock', '0004_golfcourse_player_golfround_date_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfcourse',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='golfcourse',
            name='tees',
            field=models.CharField(default='White', max_length=20),
        ),
        migrations.AddField(
            model_name='hole',
            name='golf_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superb_ock.golfcourse'),
        ),
        migrations.AddField(
            model_name='hole',
            name='par',
            field=models.IntegerField(choices=[(3, 3), (4, 4), (5, 5)], default=4),
        ),
        migrations.AddField(
            model_name='hole',
            name='yards',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='score',
            name='golf_round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superb_ock.golfround'),
        ),
        migrations.AlterField(
            model_name='golfround',
            name='event',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='second_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='hole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superb_ock.hole'),
        ),
        migrations.AlterField(
            model_name='score',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superb_ock.player'),
        ),
    ]
