# Generated by Django 5.1.7 on 2025-03-22 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superb_ock', '0005_golfcourse_country_golfcourse_tees_hole_golf_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolfEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='hole',
            name='stroke_index',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)], default=1),
        ),
        migrations.AlterField(
            model_name='golfround',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superb_ock.golfevent'),
        ),
    ]
