# Generated by Django 5.1.7 on 2025-03-22 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superb_ock', '0006_golfevent_hole_stroke_index_alter_golfround_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfround',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='superb_ock.golfevent'),
        ),
    ]
