# Generated by Django 5.1.7 on 2025-03-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superb_ock', '0007_alter_golfround_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfcourse',
            name='course_rating',
            field=models.DecimalField(decimal_places=1, default=72, max_digits=3),
        ),
        migrations.AddField(
            model_name='golfcourse',
            name='slope_rating',
            field=models.IntegerField(default=113),
        ),
        migrations.AddField(
            model_name='golfcourse',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
