# Generated by Django 5.1.7 on 2025-03-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superb_ock', '0008_golfcourse_course_rating_golfcourse_slope_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='sandy',
            field=models.BooleanField(default=False),
        ),
    ]
