# Generated by Django 5.1.7 on 2025-03-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superb_ock', '0009_score_sandy'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='handedness',
            field=models.CharField(default='Right', max_length=20),
        ),
    ]
