# Generated by Django 5.1.7 on 2025-03-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superb_ock', '0011_player_info_player_picture_player_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfround',
            name='holiday',
        ),
    ]
