# Generated by Django 5.1.7 on 2025-03-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superb_ock', '0012_remove_golfround_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfcourse',
            name='par',
            field=models.IntegerField(default=72),
        ),
    ]
