# Generated by Django 5.1.7 on 2025-04-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superb_ock', '0013_golfcourse_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfcourse',
            name='course_rating',
            field=models.FloatField(default=72),
        ),
    ]
