# Generated by Django 5.1.7 on 2025-04-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superb_ock', '0014_alter_golfcourse_course_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfevent',
            name='scoring',
            field=models.TextField(choices=[('best_three_of_five', 'Best Three of All'), ('best_last_rounds_counts', 'Best Two of First, Last Round Counts')], default='best_three_of_five', max_length=40),
        ),
    ]
