# Generated by Django 5.1.7 on 2025-05-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superb_ock', '0015_golfevent_scoring'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('video', models.FileField(upload_to='highlights')),
                ('thumbnail', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='highlight',
            field=models.ManyToManyField(blank=True, to='superb_ock.highlight'),
        ),
    ]
