# Generated by Django 5.1.7 on 2025-06-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superb_ock', '0016_highlight_score_highlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title displayed on the image', max_length=100)),
                ('description', models.TextField(help_text='Description displayed on the image', max_length=200)),
                ('image', models.ImageField(help_text='Upload carousel image', upload_to='carousel/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this image in the carousel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carousel Image',
                'verbose_name_plural': 'Carousel Images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='hole',
            name='hole_number',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18')]),
        ),
        migrations.AlterField(
            model_name='hole',
            name='par',
            field=models.IntegerField(choices=[(3, '3'), (4, '4'), (5, '5')], default=4),
        ),
        migrations.AlterField(
            model_name='hole',
            name='stroke_index',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18')], default=1),
        ),
    ]
