# Generated by Django 5.1.7 on 2025-06-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superb_ock', '0017_carouselimage_alter_hole_hole_number_alter_hole_par_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='focal_point_x',
            field=models.PositiveIntegerField(default=50, help_text='Horizontal focal point (0=left, 50=center, 100=right)'),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='focal_point_y',
            field=models.PositiveIntegerField(default=50, help_text='Vertical focal point (0=top, 50=center, 100=bottom)'),
        ),
    ]
