# Generated by Django 5.1.7 on 2025-07-12 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superb_ock', '0018_carouselimage_focal_point_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='highlights/thumbnails'),
        ),
        migrations.CreateModel(
            name='HighlightPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='highlights/previews')),
                ('timestamp', models.FloatField(help_text='Timestamp in seconds where this preview was captured')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0=first, 1=second, 2=third)')),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previews', to='superb_ock.highlight')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('highlight', 'order')},
            },
        ),
    ]
