# Generated by Django 5.1.7 on 2025-10-08 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superb_ock', '0020_userprofile'),
        ('webpush', '0006_alter_subscriptioninfo_user_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_hole_completed',
            field=models.BooleanField(default=True, help_text='Notify when you complete a hole'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_round_completed',
            field=models.BooleanField(default=True, help_text='Notify when a round is completed'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_round_start',
            field=models.BooleanField(default=True, help_text='Notify when a new round starts'),
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(help_text="User-friendly device name (e.g., 'iPhone', 'Chrome on Laptop')", max_length=100)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable notifications for this device')),
                ('subscription_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webpush.subscriptioninfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used'],
            },
        ),
    ]
