# Generated by Django 5.1.7 on 2025-10-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superb_ock', '0021_userprofile_notify_hole_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notifications_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
