# Generated by Django 5.1.7 on 2025-10-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superb_ock', '0023_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='golfround',
            name='round_event_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='score',
            name='score_round_player_idx',
        ),
        migrations.RemoveIndex(
            model_name='score',
            name='score_player_round_idx',
        ),
        migrations.AlterField(
            model_name='golfevent',
            name='scoring',
            field=models.TextField(choices=[('best_three_of_five', 'Best 3 of 5'), ('best_last_rounds_counts', 'Best Last Rounds Count')], default='best_three_of_five', max_length=40),
        ),
        migrations.AlterField(
            model_name='golfround',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='handedness',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_hole_completed',
            field=models.BooleanField(default=False, help_text='Notify when you complete a hole'),
        ),
    ]
