# Generated by Django 5.2.7 on 2025-10-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superb_ock', '0024_remove_golfround_round_event_date_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='golfround',
            options={'ordering': ['-date_started']},
        ),
        migrations.AlterModelOptions(
            name='highlight',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='highlight',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddIndex(
            model_name='golfround',
            index=models.Index(fields=['-date_started'], name='idx_round_date'),
        ),
        migrations.AddIndex(
            model_name='golfround',
            index=models.Index(fields=['event', '-date_started'], name='idx_round_event_date'),
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['-created_at'], name='idx_highlight_created'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['golf_round', 'hole'], name='idx_score_round_hole'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['golf_round', 'player'], name='idx_score_round_player'),
        ),
    ]
