# Generated by Django 5.2.7 on 2025-11-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superb_ock', '0025_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfround',
            name='use_playing_handicap',
            field=models.BooleanField(default=False, help_text='Use 95% playing handicap (England Golf standard) instead of course handicap'),
        ),
    ]
