"""
Django settings for golf2025 project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-!5774!yb)7)bi=%+x=r&n3n80=ot4onu6@5)ml4l3=i*y*&5(l'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'



INTERNAL_IPS = ['127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'superb_ock',
    'mathfilters',
    'webpush',
]

# Add development-only apps
if DEBUG:
    INSTALLED_APPS += ['django_browser_reload']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Custom error handling and logging middleware
    'superb_ock.middleware.error_handling.ErrorHandlingMiddleware',
    'superb_ock.middleware.error_handling.RequestLoggingMiddleware',
]

# Add development-only middleware
if DEBUG:
    MIDDLEWARE += ['django_browser_reload.middleware.BrowserReloadMiddleware']

# Load development overrides if available
try:
    from .dev import *
    ALLOWED_HOSTS = hosts
    INSTALLED_APPS.extend(apps)
    MIDDLEWARE.extend(middleware)
except ImportError:
    pass

# Allowed hosts configuration
if not hasattr(locals(), 'ALLOWED_HOSTS'):
    allowed_hosts_str = os.getenv(
        'ALLOWED_HOSTS',
        'localhost,127.0.0.1,www.thesuperbock.co.uk,thesuperbock.co.uk'
    )
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',')]

# Site URL
SITE_URL = os.getenv('SITE_URL', 'https://www.thesuperbock.co.uk')

# CSRF settings
csrf_origins_str = os.getenv(
    'CSRF_TRUSTED_ORIGINS',
    'https://www.thesuperbock.co.uk,https://thesuperbock.co.uk'
)
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins_str.split(',')]

# Ensure CSRF cookie is sent
CSRF_COOKIE_SECURE = not DEBUG  # Only secure in production
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read it
CSRF_COOKIE_SAMESITE = 'Lax'

ROOT_URLCONF = 'golf2025.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'superb_ock.context_processors.tournaments',
                'superb_ock.context_processors.git_version',
            ],
        },
    },
]

WSGI_APPLICATION = 'golf2025.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static/'
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Web Push Notifications
WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": os.getenv(
        'VAPID_PUBLIC_KEY',
        "BF_gEW4A2xLbFOQBC74MwscvxyBLeouPm0AkSyNdBCnapa0xpNzA7im3yizKpRYxMsDmI3GBOLJhgIFYGfkrQ0g"
    ),
    "VAPID_PRIVATE_KEY": str(BASE_DIR / os.getenv('VAPID_PRIVATE_KEY_PATH', 'vapid_private.pem')),
    "VAPID_ADMIN_EMAIL": os.getenv('VAPID_ADMIN_EMAIL', 'admin@thesuperbock.co.uk')
}

# Cache configuration
# Use local-memory cache for development, Redis for production
CACHE_BACKEND = os.getenv('CACHE_BACKEND', 'locmem')  # 'locmem' or 'redis'

if CACHE_BACKEND == 'redis':
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
            'KEY_PREFIX': 'golf2025',
            'TIMEOUT': 300,  # 5 minutes default
            'OPTIONS': {
                'MAX_ENTRIES': 1000,
            }
        }
    }
else:
    # Local-memory cache for development
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'golf2025-cache',
            'TIMEOUT': 300,  # 5 minutes default
            'OPTIONS': {
                'MAX_ENTRIES': 1000,
            }
        }
    }

# Logging configuration
LOG_LEVEL = os.getenv('LOG_LEVEL', 'INFO')
ENABLE_FILE_LOGGING = os.getenv('ENABLE_FILE_LOGGING', 'True') == 'True'
LOG_DIR = BASE_DIR / os.getenv('LOG_DIR', 'logs')

# Initialize logging
from superb_ock.logging_config import setup_logging
setup_logging(
    log_dir=LOG_DIR if ENABLE_FILE_LOGGING else None,
    level=getattr(__import__('logging'), LOG_LEVEL),
    enable_file_logging=ENABLE_FILE_LOGGING
)
